-keep class com.sun.jna.** { *; }
-keep class org.slf4j.** { *; }
-keep class net.harawata.** { *; }
-keep class com.jthemedetecor.** { *; }
-keep class com.github.oshi.** { *; }
-keep class io.github.g00fy2.** { *; }
-keep class oshi.** { *; }
-keep class org.tinylog.** { *; }
-keep class com.googlecode.plist.** { *; }

-dontwarn org.slf4j.**
-dontwarn net.harawata.**
-dontwarn com.github.oshi.**
-dontwarn io.github.g00fy2.**
-dontwarn org.tinylog.**
-dontwarn com.googlecode.plist.**
