-keep class com.sun.jna.** { *; }
-keep class org.apache.** { *; }
-keep class org.slf4j.** { *; }
-keep class net.harawata.** { *; }
-keep class io.github.g00fy2.** { *; }
-keep class com.jthemedetecor.** { *; }
-keep class com.github.oshi.** { *; }
-keep class oshi.** { *; }
-dontwarn org.apache.**
-dontwarn org.slf4j.**
-dontwarn net.harawata.**
-dontwarn io.github.g00fy2.**
-dontwarn com.github.oshi.**
-dontwarn oshi.**