name: Package release
on:
  workflow_dispatch:
  push:
    paths:
      - 'gradle/**'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - 'build.gradle.kts'
      - 'composeApp/**'
      - '.github/workflows/**'
jobs:
  package-release:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle
      - name: Test Package Release
        shell: bash
        run: |
          ./gradlew packageReleaseDistributionForCurrentOS
      - name: Show package release
        shell: bash
        run: |
          ls -l composeApp/build/packages/main-release
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            cp composeApp/build/packages/main-release/rpm/* composeApp/build/packages/main-release/deb/
            echo "ARTIFACT=composeApp/build/packages/main-release/deb/*" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            echo "ARTIFACT=composeApp/build/packages/main-release/dmg/*.dmg" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo "ARTIFACT=composeApp/build/packages/main-release/msi/*.msi" >> $GITHUB_ENV
          fi
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          body: You can get all changes [here](https://github.com/lizhongyue248/PortView/blob/master/CHANGELOG.adoc)
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            ${{env.ARTIFACT}}