name: Test
on:
  workflow_dispatch:
  push:
    paths:
      - 'gradle/**'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - 'build.gradle.kts'
      - 'composeApp/**'
      - '.github/workflows/**'
jobs:
  package-release:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: gradle
      - name: Run all test
        shell: bash
        run: |
          ./gradlew allTests